# site settings
title: Pulsipher
subtitle: Info
email: pulsipher@cmu.edu
description: A really cool guy
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://pulsipher.github.io # the base hostname & protocol for your site
author: pulsipher
street_address: Fun Street
city: Pittsburgh
state: PA
zip_code: 15217
country: USA
formspreeEndpoint: https://formspree.io/f/xaykpvzo
branch: master
repo: pulsipher/pulsipher.github.io
# google_analytics: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/pulsipher
  LinkedIn: https://www.linkedin.com/in/joshua-pulsipher
  Twitter: https://twitter.com/pulsipher42
  # Facebook: https://www.facebook.com/appsparkler

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
