# site settings
title: Bernalde
subtitle: Info
email: dbernaln@purdue.edu
description: Incoming Assistant Professor - Chemical Engineer Department
baseurl: "" # the subpath of your site, e.g. /blog
url: https://bernalde.github.io # the base hostname & protocol for your site
author: bernalde
university: Purdue University
room: Forney Hall of Chemical Engineering, 1060
street_address: 480 Stadium Mall Drive
city: West Lafayette
state: IN
zip_code: 47907-2100
country: USA
formspreeEndpoint: https://formspree.io/f/xaykpvzo
branch: master
repo: bernalde/bernalde.github.io
google_analytics: G-7SN6EM0RMM

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/bernalde
  LinkedIn: https://www.linkedin.com/in/bernalde
  Twitter: https://twitter.com/bernalde
  # Facebook: https://www.facebook.com/appsparkler

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
